Fix up languages
Brightspace/d2l-outcomes-user-progress pull request #98
Opened 2021-01-20 15:10 UTC by devpow112

This adds missing languages and also adds language verification.

2021-01-20 15:40 UTC, devpow112 commented on lang/fr-fr.json
> +    "numSearchResults": "{numResults} {numResults, plural, =1 {résultat} other {résultats}} de recherche pour « {searchTerm} »",
I think the language checker doesn't like the use of  `«`? Not sure why it dislikes this line

2021-01-25 15:43 UTC, rgoessl requested changes

2021-01-25 15:43 UTC, rgoessl commented on build/lang/en.js
> +window.D2L.language.en = {
Wouldn't this conflict with other components on the page?

2021-01-25 15:46 UTC, devpow112 commented on build/lang/en.js
> +window.D2L.language.en = {
This seems to be the way we do this. It existed before I made changes in all the other language files in the `build/lang` folder and I just followed the pattern. From some local testing it didn't come up as an issue.

2021-01-25 15:47 UTC, devpow112 commented on build/lang/en.js
> +window.D2L.language.en = {
Oh wait. NM. You mean cause I didn't namespace `language`. Yes that may cause issue. Will fix

2021-01-25 15:51 UTC, devpow112 commented on build/lang/en.js
> +window.D2L.language.en = {
Added a namespace for the language stuff

2021-01-25 16:01 UTC, rgoessl approved these changes

2021-01-25 16:03 UTC, merged